create database VENDASJOIN;
use VENDASJOIN;

create table CLIENTE(
CODIGO integer unsigned auto_increment not null,
NOME varchar(80) not null,
ENDERECO varchar(15) not null,
CIDADE varchar(15) not null,
EMAIL varchar(100) not null ,
primary key(CODIGO)
)ENGINE=INNODB;

create table USUARIOS(
NUMERO_COD integer unsigned auto_increment not null,
NOME varchar(70) not null,
LOGIN char(15) not null,
SENHA char(6) not null,
primary key(NUMERO_COD)
)ENGINE=INNODB;

create table PRODUTOS (
PRODUTO_COD integer unsigned auto_increment not null,
DESCRICAO varchar(100) not null,
VALOR DOUBLE(9,2) not null,
UNIDADE char(20) not null,
QUANTIDADE integer not null,
primary key(PRODUTO_COD)
)ENGINE=INNODB;

create table VENDAS (
VENDA_COD integer unsigned auto_increment not null,
DATA_ENTREGA date not null,
DATA_VENDA date not null,
VALOR double (9,2) not null,
CLIENTES_CODIGO integer unsigned not null,
USUARIOS_CODIGO integer unsigned not null,
primary key (VENDA_COD),
foreign key(CLIENTES_CODIGO) REFERENCES CLIENTE(CODIGO),
foreign key(USUARIOS_CODIGO) REFERENCES USUARIOS(NUMERO_COD)
)ENGINE=INNODB;

create table ITEN_VENDAS(
ITEN_COD integer unsigned auto_increment not null,
QUANTIDADE integer not null,
VALOR_UNITARIO double (9,2) not null,
VENDAS_NUMERO integer unsigned not null,
PRODUTOS_CODIGO integer unsigned not null,
primary key (ITEN_COD),
foreign key(VENDAS_NUMERO) REFERENCES VENDAS(VENDA_COD),
foreign key(PRODUTOS_CODIGO) REFERENCES PRODUTOS(PRODUTO_COD)
)ENGINE=INNODB;

create table BOLETAS(
BOLETA_COD integer unsigned auto_increment not null,
DESCRICAO varchar(80) not null,
JUROS double(9,2) not null,
MULTA double(9,2) not null,
VALOR double(9,2) not null,
DATA_BOLETA date not null,
DATA_VENCIMENTO date not null,
VENDAS_NUMERO integer unsigned not null,
primary key (BOLETA_COD),
foreign key (VENDAS_NUMERO) REFERENCES VENDAS(VENDA_COD)
)ENGINE=INNODB;

INSERT INTO CLIENTE(CODIGO, NOME, ENDERECO, CIDADE, EMAIL)
VALUES (NULL, 'ingrid', 'Rua X' , 'BH', 'ingrid@ingrid.com');
SELECT * FROM CLIENTE;

INSERT INTO USUARIOS(NUMERO_COD, NOME, LOGIN, SENHA)
VALUES (NULL, 'ingrid', 'ingridA', 123456);
SELECT * FROM USUARIOS;

INSERT INTO PRODUTOS(PRODUTO_COD, DESCRICAO, VALOR, UNIDADE, QUANTIDADE)
VALUES (NULL, 'PRODUTO', 40, 50, 40);
SELECT * FROM PRODUTOS;

INSERT INTO VENDAS(VENDA_COD, DATA_ENTREGA, DATA_VENDA, VALOR, CLIENTES_CODIGO, USUARIOS_CODIGO)
VALUES (NULL, 11/30/2020, 11/4/2020, 100, NULL, NULL);
SELECT * FROM VENDAS;

INSERT INTO ITEN_VENDAS(ITEN_COD, QUANTIDADE, VALOR_UNITARIO)
VALUES (NULL, 10, 40);
SELECT * FROM ITEN_VENDAS;

INSERT INTO BOLETAS(BOLETA_COD, DESCRICAO, JUROS, MULTA, VALOR, DATA_BOLETA, DATA_VENCIMENTO)
VALUES (NULL, 'PRODUTO', 2, 20.00, 100, 11/4/2020, 12/4/2020);
SELECT * FROM BOLETAS;

SELECT NOME, ENDERECO, CIDADE, VALOR AS VALOR_VENDAS
FROM CLIENTE JOIN VENDAS 
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO;

SELECT NOME, LOGIN, VALOR, DATA_VENDA
FROM USUARIOS JOIN VENDAS 
ON USUARIOS.NUMERO_COD = VENDAS.USUARIOS_CODIGO;

SELECT DESCRICAO, BOLETAS.VALOR, DATA
FROM BOLETAS JOIN VENDAS
ON VENDAS.VENDA_COD = BOLETAS.VENDAS_NUMERO;

SELECT DESCRICAO, VALOR_UNITARIO
FROM VENDAS JOIN INTEN_VENDAS
ON VENDAS.VENDA_COD = ITEN_VENDAS.VENDAS_NUMERO;

SELECT NOME,ENDERECO, VALOR 
FROM CLIENTE JOIN VENDAS 
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO
WHERE VENDAS.DATA_VENDA BETWEEN '2020/01/01' AND '2020/08/20';

SELECT NOME, LOGIN
FROM USUARIOS JOIN VENDAS 
ON USUARIOS.NUMERO_COD = VENDAS.USARIOS_CODIGO 
WHERE DATA_VENDA <= '2015/03/20';

SELECT DESCRICAO, VALOR
FROM PRODUTOS JOIN ITEN_VENDAS
ON PRODUTOS.PRODUTO_COD = ITEN_VENDAS.PRODUTOS-CODIGO;

SELECT SUM (VALOR)
FROM VENDAS JOIN CLIENTE
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO 
WHERE CIDADE = 'SP';

SELECT COUNT (VENDA_COD)
FROM VENDAS JOIN CLIENTE 
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO
WHERE VALOR BETWEEN 100 AND 500
AND CIDADE = 'BH';

SELECT NOME, MAX(VALOR)
FROM CLIENTE JOIN VENDAS
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO
WHERE CIDADE = 'RJ';

SELECT NOME,SUM(VENDA_COD)
FROM CLIENTE JOIN VENDAS 
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO
GROUP BY NOME
HAVING DATA_VENDA BETWEEN '2017/01/10' AND '2017/05/10';

SELECT AVG (VALOR)
FROM VENDAS JOIN CLIENTE
ON CLIENTE.CODIGO = VENDAS.CLIENTE_CODIGO
WHERE CIDADEN = 'BH'
AND DATA_VENDA <= '2017/05/30'; 

SELECT COUNT (NUMERO_COD)
FROM USUARIOS JOIN VENDAS
ON USUARIOS.NUMERO-COD = VENDAS.USARIOS_CODIGO
WHERE DATA_VENDA = '_____04___';

SELECT USUARIOS, NOME
FROM USUARIOS JOIN  VENDAS
ON USUARIOS_NUMERO_COD = VENDAS.USARIOS_CODIGO
JOIN CLIENTE 
ON CLIENTE.CODIGO = VENDAS.CLIENTES_CODIGO
WHERE CODIGO = 3;

SELECT AVH (VALOR)
FROM VENDAS JOIN CLIENTE
ON CLIENTE_CODIGO = VENDAS.CLIENTES_CODIGO
WHERE CODIGO BETWEEN 3 AND 6;

SELECT COUNT (VENDA_COD)
FROM VENDAS JOIN CLIENTE
ON CLIENTE_CODIGO = VENDAS.CLIENTES_CODIGO
WHERE NOME = 'ANDRE'
AND DATA_VENDA = '2019/02/__';