CREATE DATABASE HOTELARIA_TUMRA_1190137;
USE HOTELARIA_TURMA_1190137

CREATE TABLE(
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR (80) NOT NULL,
CPF INT USIGNED NOT NULL,
TIPO_CONVENIO VARCHAR (40) NOT NULL, PRIMARY KEY(COD)
)

CREATE TABLE SERVICO_COPA(
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
REGISTRO VARCHAR (100) NOT NULL,
TIPO_SERVICO VARCHAR (40) NOT NULL, PRIMARY KEY(COD)
)ENGINE = INNODB

CREATE TABLE RESERVA (
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
DATA_INICIO DATE UNSIGNED NOT NULL,
DATA_FIM DATE UNSIGNED NOT NULL,
QUARTO INT UNSIGNED NOT NULL,
VALOR DOUBLE (9,2) UNSIGNED NOT NULL, PRIMARY KEY(COD),
FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTE (COD)
)ENGINE = INNODB

CREATE TABLE HOSPEDE (
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR (80) NOT NULL,
TELEFONE VARCHAR (15) NOT NULL,
EMAIL VARCHAR (60) NOT NULL,
PRIMARY KEY(COD), FOREIGN KEY (RESERVA_COD) REFERENCES RESERVA (COD)
)ENGINE = INNODB

CREATE TABLE QUARTO (
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
NUMERO INT UNSIGNED NOT NULL,
ANDAR INT UNSIGNED NOT NULL,
CLASSIFICACAO VARCHAR (40) NOT NULL,
PRIMARY KEY(COD), FOREIGN KEY (HOSPEDE_COD) REFERENCES HOSPEDE (COD)
)ENGINE = INNODB

CREATE TABLE SERVICOS (
COD INT UNSIGNED AUTO_INCREMENT NOT NULL,
ITENS VARCHAR (50) NOT NULL,
TIPO VARCHAR (50) NOT NULL,
OBSERVACAO VARCHAR (100) NOT NULL,
PRIMARY KEY(COD), FOREIGN KEY (QUARTO_COD) REFERENCES QUARTO (COD),
FOREIGN KEY (SERVICO_COPA_COD) REFERENCES SERVICO_COPA (COD)
)ENGINE = INNODB

INSERT INTO CLIENTES (COD,NOME,CPF,TIPO_CONVENIO) VALUES (NULL,'INGRID',123,'OI');
INSERT INTO CLIENTES (COD,NOME,CPF,TIPO_CONVENIO) VALUES (NULL,'DIANA',012,'OII');
INSERT INTO CLIENTES (COD,NOME,CPF,TIPO_CONVENIO) VALUES (NULL,'JULIA',023,'OIII');

INSERT INTO RESERVA (COD,DATA_INICIO,DATA_FIM,QUARTO,VALOR) VALUES (NULL,2003/02/01,2020/05/04,23,50);
INSERT INTO RESERVA (COD,DATA_INICIO,DATA_FIM,QUARTO,VALOR) VALUES (NULL,2004/03/02,2021/04/05,11,60);
INSERT INTO RESERVA (COD,DATA_INICIO,DATA_FIM,QUARTO,VALOR) VALUES (NULL,2005/04/01,2022/06/08,26,70);

INSERT INTO HOSPEDE (COD,NOME,TELEFONE,EMAIL) VALUES (NULL,'INGRID','1234','INGRID@EMAIL');
INSERT INTO HOSPEDE (COD,NOME,TELEFONE,EMAIL) VALUES (NULL,'DIANA','2345','DIANA@EMAIL');
INSERT INTO HOSPEDE (COD,NOME,TELEFONE,EMAIL) VALUES (NULL,'JULIA','3456','JULIA@EMAIL');

INSERT INTO QUARTO (COD,NUMERO,ANDAR,CLASSIFICACAO) VALUES (NULL,123,2,'BOM');
INSERT INTO QUARTO (COD,NUMERO,ANDAR,CLASSIFICACAO) VALUES (NULL,321,1,'RUIM');

INSERT INTO QUARTO (COD,REGISTRO,TIPO_SERVICO) VALUES (NULL,'COLE','BOM');
INSERT INTO QUARTO (COD,REGISTRO,TIPO_SERVICO) VALUES (NULL,'OIE','RUIM');

INSERT INTO QUARTO (COD,ITENS,TIPO,OBSERVACAO) VALUES (NULL,'COMIDA','CASEIRA','MTO BOA');
INSERT INTO QUARTO (COD,ITENS,TIPO,OBSERVACAO) VALUES (NULL,'PASTEL','FRITO','MTO OLEO');
INSERT INTO QUARTO (COD,ITENS,TIPO,OBSERVACAO) VALUES (NULL,'STROGONOFF','DIGAO','SAUDADES');
INSERT INTO QUARTO (COD,ITENS,TIPO,OBSERVACAO) VALUES (NULL,'BATATA FRITA','ACAI DELICIAS','EU QUERO');

DELETE FROM RESERVA WHERE VALOR>100;
DELETE FROM HOSPEDE;
update RESERVA set valor=100.00 where data=2020/08/18;
SELECT * from RESERVA where data_inicio = 2018/05/01 between 2018/06/01;
